//gameActionTypes.ts
export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';

export const POST_GAME_REQUEST = 'POST_GAME_REQUEST';
export const POST_GAME_SUCCESS = 'POST_GAME_SUCCESS';
export const POST_GAME_FAILURE = 'POST_GAME_FAILURE';

export const GET_PLAYER_GAMES_REQUEST = 'GET_PLAYER_GAMES_REQUEST';
export const GET_PLAYER_GAMES_SUCCESS = 'GET_PLAYER_GAMES_SUCCESS';
export const GET_PLAYER_GAMES_FAILURE = 'GET_PLAYER_GAMES_FAILURE';

export const UPDATE_GAME_REQUEST = 'UPDATE_GAME_REQUEST';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';
export const UPDATE_GAME_FAILURE = 'UPDATE_GAME_FAILURE';